AWSTemplateFormatVersion: '2010-09-09'
Description: Serve X-Amz-Date with CloudFront Function

Resources:

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: x-amz.date

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: x-amz.date
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: x-amz.date
          HostedZoneId: !Ref HostedZone

  CloudFrontFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: xAmzDateFunction
      AutoPublish: true
      FunctionConfig:
        Comment: "Return current X-Amz-Date string"
        Runtime: cloudfront-js-1.0
      FunctionCode: |
        function handler(event) {
          var response = event.response;
          var now = new Date();
          var pad = (n) => n.toString().padStart(2, '0');
          var timestamp = `${now.getUTCFullYear()}${pad(now.getUTCMonth() + 1)}${pad(now.getUTCDate())}T${pad(now.getUTCHours())}${pad(now.getUTCMinutes())}${pad(now.getUTCSeconds())}Z`;
        
          response.statusCode = 200;
          response.statusDescription = 'OK';
          response.headers['content-type'] = [{ key: 'Content-Type', value: 'text/plain' }];
          response.body = {
            encoding: 'text',
            data: timestamp,
          };
          return response;
        }

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - x-amz.date
        Origins:
          - Id: dummy-origin
            DomainName: example.com
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: dummy-origin
          ViewerProtocolPolicy: redirect-to-https
          FunctionAssociations:
            - EventType: viewer-response
              FunctionARN: !GetAtt CloudFrontFunction.FunctionARN
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only

  ApexAliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZone
      Name: x-amz.date
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
